# online_rag_qa_with_reranker.yaml
# Online: question -> retrieve -> rerank -> prompt -> generate -> output

servers:
  corpus: servers/corpus
  retriever: servers/retriever
  reranker: servers/reranker
  prompt: servers/prompt
  generation: servers/generation
  benchmark: servers/benchmark
  custom: servers/custom
  evaluation: servers/evaluation

pipeline:
  - benchmark.get_data
  - retriever.retriever_init
  - retriever.retriever_search

  # NEW: rerank retrieved candidates
  - reranker.reranker_init
  - reranker.reranker_rerank

  - prompt.qa_rag_boxed
  - generation.generation_init
  - generation.generate
  - custom.output_extract_from_boxed
  - evaluation.evaluate
